// @generated by protoc-gen-es v2.2.3 with parameter "target=ts"
// @generated from file chat.proto (package chat, syntax proto3)
/* eslint-disable */

import type { GenFile, GenMessage, GenService } from "@bufbuild/protobuf/codegenv1";
import { fileDesc, messageDesc, serviceDesc } from "@bufbuild/protobuf/codegenv1";
import type { Message } from "@bufbuild/protobuf";

/**
 * Describes the file chat.proto.
 */
export const file_chat: GenFile = /*@__PURE__*/
  fileDesc("CgpjaGF0LnByb3RvEgRjaGF0IjEKElNlbmRNZXNzYWdlUmVxdWVzdBIKCgJpZBgBIAEoCRIPCgdtZXNzYWdlGAIgASgJIhUKE1NlbmRNZXNzYWdlUmVzcG9uc2UiHgoQT25NZXNzYWdlUmVxdWVzdBIKCgJpZBgBIAEoCSIwChFPbk1lc3NhZ2VSZXNwb25zZRIKCgJpZBgBIAEoCRIPCgdtZXNzYWdlGAIgASgJMpEBCgtDaGF0U2VydmljZRJCCgtzZW5kTWVzc2FnZRIYLmNoYXQuU2VuZE1lc3NhZ2VSZXF1ZXN0GhkuY2hhdC5TZW5kTWVzc2FnZVJlc3BvbnNlEj4KCW9uTWVzc2FnZRIWLmNoYXQuT25NZXNzYWdlUmVxdWVzdBoXLmNoYXQuT25NZXNzYWdlUmVzcG9uc2UwAWIGcHJvdG8z");

/**
 * @generated from message chat.SendMessageRequest
 */
export type SendMessageRequest = Message<"chat.SendMessageRequest"> & {
  /**
   * @generated from field: string id = 1;
   */
  id: string;

  /**
   * @generated from field: string message = 2;
   */
  message: string;
};

/**
 * Describes the message chat.SendMessageRequest.
 * Use `create(SendMessageRequestSchema)` to create a new message.
 */
export const SendMessageRequestSchema: GenMessage<SendMessageRequest> = /*@__PURE__*/
  messageDesc(file_chat, 0);

/**
 * @generated from message chat.SendMessageResponse
 */
export type SendMessageResponse = Message<"chat.SendMessageResponse"> & {
};

/**
 * Describes the message chat.SendMessageResponse.
 * Use `create(SendMessageResponseSchema)` to create a new message.
 */
export const SendMessageResponseSchema: GenMessage<SendMessageResponse> = /*@__PURE__*/
  messageDesc(file_chat, 1);

/**
 * @generated from message chat.OnMessageRequest
 */
export type OnMessageRequest = Message<"chat.OnMessageRequest"> & {
  /**
   * @generated from field: string id = 1;
   */
  id: string;
};

/**
 * Describes the message chat.OnMessageRequest.
 * Use `create(OnMessageRequestSchema)` to create a new message.
 */
export const OnMessageRequestSchema: GenMessage<OnMessageRequest> = /*@__PURE__*/
  messageDesc(file_chat, 2);

/**
 * @generated from message chat.OnMessageResponse
 */
export type OnMessageResponse = Message<"chat.OnMessageResponse"> & {
  /**
   * @generated from field: string id = 1;
   */
  id: string;

  /**
   * @generated from field: string message = 2;
   */
  message: string;
};

/**
 * Describes the message chat.OnMessageResponse.
 * Use `create(OnMessageResponseSchema)` to create a new message.
 */
export const OnMessageResponseSchema: GenMessage<OnMessageResponse> = /*@__PURE__*/
  messageDesc(file_chat, 3);

/**
 * @generated from service chat.ChatService
 */
export const ChatService: GenService<{
  /**
   * @generated from rpc chat.ChatService.sendMessage
   */
  sendMessage: {
    methodKind: "unary";
    input: typeof SendMessageRequestSchema;
    output: typeof SendMessageResponseSchema;
  },
  /**
   * @generated from rpc chat.ChatService.onMessage
   */
  onMessage: {
    methodKind: "server_streaming";
    input: typeof OnMessageRequestSchema;
    output: typeof OnMessageResponseSchema;
  },
}> = /*@__PURE__*/
  serviceDesc(file_chat, 0);

