name: CI

on:
  push:
  pull_request:

jobs:
  ci:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v5
        with:
          fetch-depth: 2

      - uses: actions/setup-node@v6.0.0
        with:
          node-version-file: .nvmrc

      - run: npm ci

      - run: npx prettier --check .

      - run: npm run build

      - run: npm run test

      - uses: mnao305/chrome-extension-upload@v5.0.0
        if: ${{ github.ref == 'refs/heads/main' && contains(github.event.head_commit.message, 'chore(release):') }}
        with:
          file-path: dist.zip
          extension-id: fohdnlaeecihjiendkfhifhlgldpeopm
          client-id: ${{ secrets.CLIENT_ID }}
          client-secret: ${{ secrets.CLIENT_SECRET }}
          refresh-token: ${{ secrets.REFRESH_TOKEN }}
